POST https://nacb-progweb-backend.azurewebsites.net/reserva
Content-Type: application/json

{
    "fechaReserva": "2023-11-18",
    "fechaDevolucion": "2023-11-20",
    "idUsuario": 1,
    "idLibro": 2
}

########

POST https://nacb-progweb-backend.azurewebsites.net/reserva
Content-Type: application/json

{
    "fechaReserva": "2023-11-23",
    "fechaDevolucion": "2023-12-12",
    "idUsuario": 3,
    "idLibro": 3
}

########

GET  https://nacb-progweb-backend.azurewebsites.net/reserva/libros/1